### PR TITLE
feat: remember current user when log in.

### LINKED ISSUE #34: Auto Login
If I want to create a bookmark, I first have to open the interface and login there. It would be better if the plugin automatically login if no session already exists.

Note: I use the plugin with Chrome

### PR DESCRIPTION
**Pull request by IvanLi-CN**
I added the Remember Me option to the configuration screen to allow the server to provide long-term (currently 30 days) session.

image

It probably resolves #34.

### CODE REVIEW

**Comment by axelsimon** [comment]
@RadhiFadlillah or @fmartingr can you review and merge?

FWIW, i'd say it looks good to me.

**Comment by fmartingr** [comment]
Hey! Looks good to me but CI is failing atm. I need to check what's going on there first. Let me see if I can spare some time this evening to fix that.

**Comment by fmartingr** [comment]
I have run the lint manually and it passes, so I'm merging this since I can't re-run the pipeline now.

**Comment by johnchristopher** [comment]
Hi,

The extension on firefox website is still 0.8.4 and doesn't have this feature.

I was wondering why the session was limited to one hour and then searching for a fix and finding this commit why there were no "remember me" check box (in Firefox extension).

**Pull request merged**
