### PR TITLE
feat: add custom search-engine to query shiori

### PR DESCRIPTION
**Pull request by patrickpichler**
It is now possible to query Shiori directly from the firefox search bar by simply prefixing the query with `@shiori`. This will trigger a shiori keyword search. It is also possible to search by tags, by prefixing words with `#`.

fixes: #58

### CODE REVIEW

**Comment by fmartingr** [comment]
Hey @patrickpichler thanks for the contribution! This seems super useful. One question before a proper review, how will browsers that don't support omnibox react to this? Will the execution break since `browser.omnibox` is not defined?

**Comment by patrickpichler** [comment]
Great question, I have no idea tbh! Is the extension supported for Safari?

**Comment by patrickpichler** [comment]
Sounds good 👌 🙂 
I will add it!

**Comment by patrickpichler** [comment]
I wrapped it in an if :)

**Review by fmartingr — APPROVED** [review]
This seems a great addition, didn't knew about the omnibar exposed APIs. :) Thanks for your work!

**Pull request merged**
